#  Handling Missing Data with Pandas

In this notebook, we will learn:

1. What missing data means
2. How to detect missing values
3. How to count missing values
4. How to remove missing rows
5. How to remove missing columns
6. How to fill missing values
7. Filling with mean
8. Filling with median
9. Filling with mode
10. Forward fill and backward fill
11. Choosing the right strategy for ML

In [1]:
# Import Pandas
import pandas as pd

In [2]:
# Create a dataset containing missing values

data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Rohan", "Devi"],
    "Age": [20, 21, None, 22, 23, None],
    "Marks": [85, None, 76, 92, None, 88],
    "Department": ["CSE", "ECE", "CSE", None, "ECE", "CSE"]
}

df = pd.DataFrame(data)

print(df)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0    NaN        ECE
2   Amit   NaN   76.0        CSE
3  Sneha  22.0   92.0        NaN
4  Rohan  23.0    NaN        ECE
5   Devi   NaN   88.0        CSE

## Detect Missing Values

In [3]:
# Check which values are missing
print(df.isnull())

    Name    Age  Marks  Department
0  False  False  False       False
1  False  False   True       False
2  False   True  False       False
3  False  False  False        True
4  False  False   True       False
5  False   True  False       False

## Count Missing Values

In [4]:
# Count missing values in each column
print(df.isnull().sum())

Name          0
Age           2
Marks         2
Department    1
dtype: int64

## Count All Missing Values

In [5]:
# Count all missing values in the entire DataFrame
print(df.isnull().sum().sum())

5

In [6]:
df.isnull()

    Name    Age  Marks  Department
0  False  False  False       False
1  False  False   True       False
2  False   True  False       False
3  False  False  False        True
4  False  False   True       False
5  False   True  False       False

In [7]:
df.isna()

    Name    Age  Marks  Department
0  False  False  False       False
1  False  False   True       False
2  False   True  False       False
3  False  False  False        True
4  False  False   True       False
5  False   True  False       False

In [8]:
print(df.isna().sum())

Name          0
Age           2
Marks         2
Department    1
dtype: int64

## Find Rows Containing Missing Values

In [10]:
# Display rows containing at least one missing value
print(df[df.isnull().any(axis=1)])

    Name   Age  Marks Department
1  Priya  21.0    NaN        ECE
2   Amit   NaN   76.0        CSE
3  Sneha  22.0   92.0        NaN
4  Rohan  23.0    NaN        ECE
5   Devi   NaN   88.0        CSE

## Find Rows With No Missing Values

In [11]:
# Display rows that contain no missing values
print(df[df.notnull().all(axis=1)])

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE

## Remove Rows Containing Missing Values

In [12]:
# Create a copy of the original DataFrame
df_drop = df.copy()

# Remove rows containing missing values
df_drop = df_drop.dropna()

print(df_drop)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE

## Remove Rows Based on a Specific Column

In [13]:
# Remove rows where Marks is missing
df_marks = df.dropna(subset=["Marks"])

print(df_marks)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
2   Amit   NaN   76.0        CSE
3  Sneha  22.0   92.0        NaN
5   Devi   NaN   88.0        CSE

## Remove Columns Containing Missing Values

In [14]:
# Create a copy
df_columns = df.copy()

# Remove columns containing at least one missing value
df_columns = df_columns.dropna(axis=1)

print(df_columns)

    Name
0  Rahul
1  Priya
2   Amit
3  Sneha
4  Rohan
5   Devi

## Filling Missing Values

In [15]:
# Create a copy
df_fill = df.copy()

# Replace missing Age values with 0
df_fill["Age"] = df_fill["Age"].fillna(0)

print(df_fill)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0    NaN        ECE
2   Amit   0.0   76.0        CSE
3  Sneha  22.0   92.0        NaN
4  Rohan  23.0    NaN        ECE
5   Devi   0.0   88.0        CSE

## Fill With Mean

In [16]:
# Create a copy
df_mean = df.copy()

# Calculate the mean Age
age_mean = df_mean["Age"].mean()

print("Mean Age:", age_mean)

Mean Age: 21.5

In [17]:
# Fill missing Age values with the mean Age
df_mean["Age"] = df_mean["Age"].fillna(age_mean)

print(df_mean)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0    NaN        ECE
2   Amit  21.5   76.0        CSE
3  Sneha  22.0   92.0        NaN
4  Rohan  23.0    NaN        ECE
5   Devi  21.5   88.0        CSE

In [19]:
df_mean["Age"] = df_mean["Age"].fillna(df_mean["Age"].mean())
print(df_mean)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0    NaN        ECE
2   Amit  21.5   76.0        CSE
3  Sneha  22.0   92.0        NaN
4  Rohan  23.0    NaN        ECE
5   Devi  21.5   88.0        CSE

## Fill With Median

In [20]:
# Create a copy
df_median = df.copy()

# Calculate the median Age
age_median = df_median["Age"].median()

print("Median Age:", age_median)

Median Age: 21.5

In [21]:
# Fill missing Age values with the median
df_median["Age"] = df_median["Age"].fillna(age_median)

print(df_median)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0    NaN        ECE
2   Amit  21.5   76.0        CSE
3  Sneha  22.0   92.0        NaN
4  Rohan  23.0    NaN        ECE
5   Devi  21.5   88.0        CSE

In [22]:
df_median["Age"] = df_median["Age"].fillna(df_median["Age"].median())
print(df_median)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0    NaN        ECE
2   Amit  21.5   76.0        CSE
3  Sneha  22.0   92.0        NaN
4  Rohan  23.0    NaN        ECE
5   Devi  21.5   88.0        CSE

## Fill Categorical Data with Mode

In [23]:
# Find the most common department
department_mode = df["Department"].mode()[0]

print("Most common department:", department_mode)

Most common department: CSE

In [25]:
# Fill missing Department values with the mode
df_mode = df.copy()

df_mode["Department"] = df_mode["Department"].fillna(
    df_mode["Department"].mode()[0]
)

print(df_mode)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0    NaN        ECE
2   Amit   NaN   76.0        CSE
3  Sneha  22.0   92.0        CSE
4  Rohan  23.0    NaN        ECE
5   Devi   NaN   88.0        CSE

## Filling Different Columns Differently
    Age → numerical
    Marks → numerical
    Department → categorical

In [26]:
# Create a copy
df_clean = df.copy()

# Fill numerical columns using median
df_clean["Age"] = df_clean["Age"].fillna(
    df_clean["Age"].median()
)

df_clean["Marks"] = df_clean["Marks"].fillna(
    df_clean["Marks"].median()
)

# Fill categorical column using mode
df_clean["Department"] = df_clean["Department"].fillna(
    df_clean["Department"].mode()[0]
)

print(df_clean)

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0   86.5        ECE
2   Amit  21.5   76.0        CSE
3  Sneha  22.0   92.0        CSE
4  Rohan  23.0   86.5        ECE
5   Devi  21.5   88.0        CSE

## Forward Fill

In [27]:
# Create a simple Series
values = pd.Series([10, None, None, 40, 50])

# Fill missing values using the previous value
print(values.ffill())

0    10.0
1    10.0
2    10.0
3    40.0
4    50.0
dtype: float64

## Backward Fill

In [28]:
# Fill missing values using the next available value
print(values.bfill())

0    10.0
1    40.0
2    40.0
3    40.0
4    50.0
dtype: float64

In [29]:
# Check missing values after cleaning
print(df_clean.isnull().sum())

Name          0
Age           0
Marks         0
Department    0
dtype: int64

In [30]:
df_clean

    Name   Age  Marks Department
0  Rahul  20.0   85.0        CSE
1  Priya  21.0   86.5        ECE
2   Amit  21.5   76.0        CSE
3  Sneha  22.0   92.0        CSE
4  Rohan  23.0   86.5        ECE
5   Devi  21.5   88.0        CSE