#  Duplicates and Data Cleaning

Real-world datasets are often messy.

Problems can include:

- Duplicate rows
- Duplicate records
- Extra spaces
- Inconsistent capitalization
- Incorrect values
- Wrong data types
- Invalid values
- Inconsistent category names

In this notebook, we will learn how to identify and
fix these common problems using Pandas.

In [110]:
# Import Pandas
import pandas as pd

In [111]:
# Create a dataset containing some messy data

data = {
    "Name": [
        "Rahul",
        "Priya",
        "Amit",
        "Sneha",
        "Rahul",
        "  Rohan  "
    ],
    
    "Age": [
        20,
        21,
        22,
        20,
        20,
        23
    ],
    
    "Department": [
        "CSE",
        "ECE",
        "cse",
        "CSE ",
        "CSE",
        "ece"
    ],
    
    "Marks": [
        85,
        90,
        76,
        92,
        85,
        68
    ]
}

df = pd.DataFrame(data)

print(df)

        Name  Age Department  Marks
0      Rahul   20        CSE     85
1      Priya   21        ECE     90
2       Amit   22        cse     76
3      Sneha   20       CSE      92
4      Rahul   20        CSE     85
5    Rohan     23        ece     68

## Check Duplicate Rows

In [112]:
# Check which rows are duplicates
print(df.duplicated())

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

## Count Duplicate Rows

In [113]:
# Count the number of duplicate rows
print(df.duplicated().sum())

1

## Display Duplicate Rows

In [114]:
# Display only duplicate rows
duplicates = df[df.duplicated()]

print(duplicates)

    Name  Age Department  Marks
4  Rahul   20        CSE     85

## Remove Duplicate Rows

In [115]:
# Remove duplicate rows
df_clean = df.drop_duplicates()

print(df_clean)

        Name  Age Department  Marks
0      Rahul   20        CSE     85
1      Priya   21        ECE     90
2       Amit   22        cse     76
3      Sneha   20       CSE      92
5    Rohan     23        ece     68

## Reset the Index

In [116]:
# Reset the index after removing duplicates
df_clean = df_clean.reset_index(drop=True)

print(df_clean)

        Name  Age Department  Marks
0      Rahul   20        CSE     85
1      Priya   21        ECE     90
2       Amit   22        cse     76
3      Sneha   20       CSE      92
4    Rohan     23        ece     68

## Duplicate Based on Specific Columns

In [117]:
# Check duplicates based on Name and Age
print(df.duplicated(subset=["Name", "Age"]))

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

## Remove Duplicates Based on Specific Columns

In [118]:
# Remove duplicates based on Name and Age
df_unique = df.drop_duplicates(
    subset=["Name", "Age"]
)

print(df_unique)

        Name  Age Department  Marks
0      Rahul   20        CSE     85
1      Priya   21        ECE     90
2       Amit   22        cse     76
3      Sneha   20       CSE      92
5    Rohan     23        ece     68

## Remove Spaces from Text

In [119]:
# Remove leading and trailing spaces from Name
df["Name"] = df["Name"].str.strip()

print(df)

    Name  Age Department  Marks
0  Rahul   20        CSE     85
1  Priya   21        ECE     90
2   Amit   22        cse     76
3  Sneha   20       CSE      92
4  Rahul   20        CSE     85
5  Rohan   23        ece     68

## Convert Text to Lowercase

In [120]:
# Convert Department values to lowercase
df["Department"] = df["Department"].str.lower()

print(df)

    Name  Age Department  Marks
0  Rahul   20        cse     85
1  Priya   21        ece     90
2   Amit   22        cse     76
3  Sneha   20       cse      92
4  Rahul   20        cse     85
5  Rohan   23        ece     68

## Remove Spaces and Convert Case

In [121]:
# Remove spaces and convert Department to uppercase
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
)

print(df["Department"])

0    CSE
1    ECE
2    CSE
3    CSE
4    CSE
5    ECE
Name: Department, dtype: str

## Check Categories After Cleaning

In [122]:
# Check unique Department values
print(df["Department"].unique())

<StringArray>
['CSE', 'ECE']
Length: 2, dtype: str

In [123]:
print(df["Department"].value_counts())

Department
CSE    4
ECE    2
Name: count, dtype: int64

## Replace Incorrect Values

In [124]:
# Replace incorrect category
df["Department"] = df["Department"].replace(
    "CS",
    "CSE"
)

In [125]:
# multiple replacements:

df["Department"] = df["Department"].replace({
    "CS": "CSE",
    "Computer Science": "CSE"
})

## Detect Invalid Numerical Values

In [126]:
# Create an example with an invalid age
df.loc[0, "Age"] = -5

print(df)

    Name  Age Department  Marks
0  Rahul   -5        CSE     85
1  Priya   21        ECE     90
2   Amit   22        CSE     76
3  Sneha   20        CSE     92
4  Rahul   20        CSE     85
5  Rohan   23        ECE     68

In [127]:
# Find rows with invalid ages
invalid_age = df[df["Age"] < 0]

print(invalid_age)

    Name  Age Department  Marks
0  Rahul   -5        CSE     85

## Replace Invalid Values with Missing Values

In [128]:
# Replace invalid ages with NaN
df.loc[df["Age"] < 0, "Age"] = None

print(df)

    Name   Age Department  Marks
0  Rahul   NaN        CSE     85
1  Priya  21.0        ECE     90
2   Amit  22.0        CSE     76
3  Sneha  20.0        CSE     92
4  Rahul  20.0        CSE     85
5  Rohan  23.0        ECE     68

In [129]:
df["Age"] = df["Age"].fillna(
    df["Age"].median()
)
df

    Name   Age Department  Marks
0  Rahul  21.0        CSE     85
1  Priya  21.0        ECE     90
2   Amit  22.0        CSE     76
3  Sneha  20.0        CSE     92
4  Rahul  20.0        CSE     85
5  Rohan  23.0        ECE     68

## Detect Invalid Marks

In [130]:
# Find invalid marks
invalid_marks = df[
    (df["Marks"] < 0) |
    (df["Marks"] > 100)
]

print(invalid_marks)

Empty DataFrame
Columns: [Name, Age, Department, Marks]
Index: []

## Convert Text Numbers to Numeric.

In [131]:
# Create an example DataFrame
salary_df = pd.DataFrame({
    "Salary": ["25000", "30000", "35000", "unknown"]
})

print(salary_df)
print(salary_df.dtypes)

    Salary
0    25000
1    30000
2    35000
3  unknown
Salary    str
dtype: object

In [132]:
# Convert Salary to numeric
salary_df["Salary"] = pd.to_numeric(
    salary_df["Salary"],
    errors="coerce"
)

print(salary_df)

    Salary
0  25000.0
1  30000.0
2  35000.0
3      NaN

## Remove Duplicate Names

In [133]:
# Remove duplicate names
df = df.drop_duplicates(
    subset=["Name"]
)

print(df)

    Name   Age Department  Marks
0  Rahul  21.0        CSE     85
1  Priya  21.0        ECE     90
2   Amit  22.0        CSE     76
3  Sneha  20.0        CSE     92
5  Rohan  23.0        ECE     68

## Rename Columns for Consistency

In [134]:
# Example DataFrame
messy_columns = pd.DataFrame({
    "Student Name": ["A", "B"],
    "student_age": [20, 21],
    "MARKS": [80, 90]
})

print(messy_columns)

  Student Name  student_age  MARKS
0            A           20     80
1            B           21     90

In [135]:
# Standardize column names
messy_columns = messy_columns.rename(columns={
    "Student Name": "student_name",
    "student_age": "age",
    "MARKS": "marks"
})

print(messy_columns)

  student_name  age  marks
0            A   20     80
1            B   21     90

## Remove Extra Spaces from Column Names

In [136]:
# Remove extra spaces from all column names
df.columns = df.columns.str.strip()

print(df.columns)

Index(['Name', 'Age', 'Department', 'Marks'], dtype='str')

## Convert Column Names to Lowercase

In [137]:
df.columns = df.columns.str.strip().str.lower()
df

    name   age department  marks
0  Rahul  21.0        CSE     85
1  Priya  21.0        ECE     90
2   Amit  22.0        CSE     76
3  Sneha  20.0        CSE     92
5  Rohan  23.0        ECE     68

## A Practical Cleaning Pipeline

In [138]:
# Create a messy dataset

data = {
    "Name": [" Rahul ", "Priya", "Amit", "Rahul"],
    "Age": [20, 21, -5, 20],
    "Department": ["CSE", "cse", " CSE ", "CSE"],
    "Marks": [85, 90, 76, 85]
}

df = pd.DataFrame(data)

print(df)

      Name  Age Department  Marks
0   Rahul    20        CSE     85
1    Priya   21        cse     90
2     Amit   -5       CSE      76
3    Rahul   20        CSE     85

In [139]:
# Step 2: Identify invalid ages

print(df[df["Age"] < 0])

   Name  Age Department  Marks
2  Amit   -5       CSE      76

In [144]:
# Replace invalid ages with NaN
df.loc[df["Age"] < 0, "Age"] = None
df

      Name   Age Department  Marks
0   Rahul   20.0        CSE     85
1    Priya  21.0        cse     90
2     Amit   NaN       CSE      76
3    Rahul  20.0        CSE     85

In [145]:
# Step 4: Fill missing Age values using the median

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

print(df)

      Name   Age Department  Marks
0   Rahul   20.0        CSE     85
1    Priya  21.0        cse     90
2     Amit  20.0       CSE      76
3    Rahul  20.0        CSE     85

In [146]:
# Step 5: Remove duplicate records

df = df.drop_duplicates(
    subset=["Name", "Age", "Department", "Marks"]
)

# Reset the index
df = df.reset_index(drop=True)

print(df)

      Name   Age Department  Marks
0   Rahul   20.0        CSE     85
1    Priya  21.0        cse     90
2     Amit  20.0       CSE      76
3    Rahul  20.0        CSE     85

In [147]:
# Step 6: Final inspection

print("Shape:")
print(df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nUnique departments:")
print(df["Department"].unique())

print("\nData types:")
print(df.dtypes)

Shape:
(4, 4)

Missing values:
Name          0
Age           0
Department    0
Marks         0
dtype: int64

Duplicate rows:
0

Unique departments:
<StringArray>
['CSE', 'cse', ' CSE ']
Length: 3, dtype: str

Data types:
Name              str
Age           float64
Department        str
Marks           int64
dtype: object